package com.aldikitta.jetmeditationui.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryDark = Color(0xFFD0BCFF)
val OnPrimaryDark = Color(0xff381e72)
val PrimaryContainerDark = Color(0xff4f378b)
val OnPrimaryContainerDark = Color(0xffeaddff)
val InversePrimaryDark = Color(0xff6750a4)
val SecondaryDark = Color(0xffccc2dc)
val OnSecondaryDark = Color(0xff332d41)
val SecondaryContainerDark = Color(0xff4a4458)
val OnSecondaryContainerDark = Color(0xffe8def8)
val TertiaryDark = Color(0xffefb8c8)
val OnTertiaryDark = Color(0xff492532)
val TertiaryContainerDark = Color(0xff633b48)
val OnTertiaryContainerDark = Color(0xffffd8e4)
val BackgroundDark = Color(0xff1c1b1f)
val OnBackgroundDark = Color(0xffe6e1e5)
val SurfaceDark = Color(0xff1c1b1f)
val OnSurfaceDark = Color(0xffe6e1e5)



val PrimaryLight = Color(0xff6750a4)
val OnPrimaryLight = Color(0xffffffff)
val PrimaryContainerLight = Color(0xffeaddff)
val OnPrimaryContainerLight = Color(0xff21005d)
val InversePrimaryLight = Color(0xffd0bcff)
val SecondaryLight = Color(0xff625b71)
val OnSecondaryLight = Color(0xffffffff)
val SecondaryContainerLight = Color(0xffe8def8)
val OnSecondaryContainerLight = Color(0xff1d192b)
val TertiaryLight = Color(0xff7d5260)
val OnTertiaryLight = Color(0xffffffff)
val TertiaryContainerLight = Color(0xffffd8e4)
val OnTertiaryContainerLight = Color(0xff31111d)
val BackgroundLight = Color(0xfffffbfe)
val OnBackgroundLight = Color(0xff1c1b1f)
val SurfaceLight = Color(0xfffffbfe)
val OnSurfaceLight = Color(0xff1c1b1f)

val OrangeYellow1 = Color(0xfff0bd28)
val OrangeYellow2 = Color(0xfff1c746)
val OrangeYellow3 = Color(0xfff4cf65)
val Beige1 = Color(0xfffdbda1)
val Beige2 = Color(0xfffcaf90)
val Beige3 = Color(0xfff9a27b)
val LightGreen1 = Color(0xff54e1b6)
val LightGreen2 = Color(0xff36ddab)
val LightGreen3 = Color(0xff11d79b)
val BlueViolet1 = Color(0xffaeb4fd)
val BlueViolet2 = Color(0xff9fa5fe)
val BlueViolet3 = Color(0xff8f98fd)